apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tkn-rhtap-5279
  janus-idp.io/tekton: tkn-rhtap-5279
  backstage.io/kubernetes-id: tkn-rhtap-5279
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tkn-rhtap-5279
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
