apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tkn-rhtap-5279
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tkn-rhtap-5279 
  name: tkn-rhtap-5279
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tkn-rhtap-5279 
