apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tkn-rhtap-5279
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/lucarval-rhtap/tkn-rhtap-5279:2d68d5ff3b259ef13557de490cce2bd83051d756@sha256:8f8d75dcca0bf37ab25cb73e9b800990518f512ff6cbb81d7bc73f40d13a926b
          name: container-image
